<option value="cat5_1"><?php echo e(__('categories.cat5_1')); ?></option>
<option value="cat5_2"><?php echo e(__('categories.cat5_2')); ?></option>
<option value="cat5_3"><?php echo e(__('categories.cat5_3')); ?></option>
<option value="cat5_4"><?php echo e(__('categories.cat5_4')); ?></option>
<option value="cat5_5"><?php echo e(__('categories.cat5_5')); ?></option>
<option value="cat5_6"><?php echo e(__('categories.cat5_6')); ?></option>
<option value="cat5_7"><?php echo e(__('categories.cat5_7')); ?></option>
<option value="cat5_8"><?php echo e(__('categories.cat5_8')); ?></option>
<?php /**PATH /home/nanstis/PhpstormProjects/pb-live/resources/views/common/subcat5.blade.php ENDPATH**/ ?>